name: python 3.9
channels:
  - astropy
  - anaconda
  - conda-forge
dependencies:
  - python=3.9.16
  - numpy=1.23.5
  - matplotlib-base=3.6.2
  - pandas=1.5.3
  - stingray=1.1.2
  - astropy=5.3.4
  - seaborn=0.12.2
  - scipy=1.10.0
